backend:
  name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: master # Branch to update
  repo: yoppoy/entrepreneur-site-gatsby # Repo for pushing new commits. Make sure to replace with your repo!

media_folder: static/assets
public_folder: assets

collections:
  - name: timeline-event
    label: "Post"
    folder: "content"
    create: true
    fields:
      - { label: "Contract Type", name: "type", widget: "string" }
      - { label: "Contract title", name: "title", widget: "string" }
      - { label: "Contract Description", name: "descrition", widget: "list" }
      - { label: "Start Date", name: "date", widget: "datetime" }
      - { label: "End Date", name: "date", widget: "datetime" }
      - { label: "Employer Name", name: "employerName", widget: "string" }
      - { label: "Employer Logo", name: "employerLogo", widget: "image" }
      - { label: "Devicons", name: "icons", widget: "list" }
