backend:
  name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: master # Branch to update
  repo: yoppoy/entrepreneur-site-gatsby # Repo for pushing new commits. Make sure to replace with your repo!

media_folder: static/assets
public_folder: assets

collections:
  - label: "Languages"
    name: "languages"
    folder: "content/languages"
    extension: "yml"
    format: "yml"
    create: false
    slug: "{{code}}"
    editor:
      preview: false
    fields:
      - { label: "Language", name: "language" , widget: string}
      - { label: "Country Code (for url)", name: "code" , widget: string}
  - label: "Experiences"
    name: "experiences"
    folder: "content/experiences"
    create: true
    slug: "{{employerName}}-{{year}}.{{language}}"
    fields:
      - {
        label: "Language",
        name: "language",
        widget: "relation",
        collection: "languages",
        searchFields: ["language"],
        valueField: "code",
        displayFields: ["language"],
        default: "fr"
      }
      - { label: "Contract Type", name: "type", widget: "string" }
      - { label: "Contract title", name: "title", widget: "string" }
      - { label: "Contract Description", name: "description", widget: "markdown" }
      - { label: "Start Date", name: "dateStart", widget: "datetime" }
      - { label: "End Date", name: "dateEnd", widget: "datetime" }
      - { label: "Employer Name", name: "employerName", widget: "string" }
      - { label: "Employer Logo", name: "employerLogo", widget: "image" }
      - { label: "Devicons", name: "icons", widget: "list" }
  - label: "Testimonies"
    name: "testimonies"
    folder: "content/testimonies"
    create: true
    slug: "{{company}}-{{fullName}}.{{language}}"
    fields:
      - {
        label: "Language",
        name: "language",
        widget: "relation",
        collection: "languages",
        searchFields: ["language"],
        valueField: "code",
        displayFields: ["language"],
        default: "fr"
      }
      - { label: "Full Name", name: "fullName", widget: "string" }
      - { label: "Testimony", name: "testimony", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Job Title", name: "job", widget: "string" }
